### ISSUE TITLE
ENH: Refactor AEF timing into separate function

### ISSUE THREAD

**Issue by larsoner** [Macquarie-MEG-Research/natural_conversations#3]
I'm working on a script to BIDSify the dataset so I can put it through [MNE-BIDS-Pipeline](https://mne.tools/mne-bids-pipeline). It would be helpful if the trigger realignment code from https://github.com/Macquarie-MEG-Research/natural_conversations/blob/main/simple_AEF_AEP.py were refactored into:

1. A separate importable module (e.g., `utils.py` or similar)
2. A function within that module that took a filename or (better) `raw` instance, extracted triggers, analyzed mic data, and realigned/recreated triggers based on the extracted data, and returned an `events` ndarray suitable for creating `mne.Epochs(raw, events, ...)`

Then MNE-BIDS-Pipeline will give us the AEFs (almost) for free.

**Comment by larsoner** [comment]
@JD-Zhu I can try to do the refactoring suggested above if it would help, but it would probably be quicker for you assuming you wrote `simple_AEF_AEP.py`

**Comment by JD-Zhu** [comment]
Thanks @larsoner . I will have a go at this tomorrow!

Would you mind also sharing your code for aligning and concatenating the MEG and EEG data? Yifan is doing some explorations on the data and it would be great to look at combined MEG and EEG if possible.

**Comment by JD-Zhu** [comment]
I have now separated the trigger timing correction code into utils.py - please let me know if this looks okay @larsoner 

The function is currently also returning the audio delay values themselves, as these are used again for timing correction of EEG data later on in simple_AEF_AEP.py (when we align and concatenate the MEG and EEG data, this will no longer be required)

**Comment by larsoner** [comment]
Thanks. Yes I can push the sync code early next week, just want to get it pumping through MNE-BIDS-Pipeline so I need to take care of a limitation there first, but I don't think that will be too bad!

**Comment by JD-Zhu** [comment]
Thanks!
